
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cachet.fullname }}
  labels: 
    app: {{ .Values.cachet.labels }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.cachet.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.cachet.labels }}
    spec:
      containers:
      - name: {{ .Values.cachet.fullname }}
        image: "{{ .Values.cachet.image.repository }}:{{ .Values.cachet.image.tag }}"
        imagePullPolicy: {{ .Values.cachet.image.pullPolicy }}
        resources:
          limits:
            memory: {{ .Values.cachet.container.size}}
            cpu: {{ .Values.cachet.container.CPU}}
        ports:
          - containerPort: {{ .Values.cachet.service.port }}
        env:
          {{- range $key, $val := .Values.cachet.env }}
            {{ printf "- name: %s" $key }}
            {{ printf "  value: %s" ( $val | quote ) }}   
          {{- end }}   
