
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cachet.fullname }}
  labels: 
    app: {{ .Values.cachet.labels }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.cachet.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.cachet.labels }}
    spec:
      containers:
      - name: {{ .Values.cachet.fullname }}
        image: "{{ .Values.cachet.image.repository }}:{{ .Values.cachet.image.tag }}"
        imagePullPolicy: {{ .Values.cachet.image.pullPolicy }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: {{ .Values.cachet.service.port }}
        env:
        {{- include "helper.env.var" . | indent 6 }}

