apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.kuma.volumes.volumeClaimName }}
  labels:
    app: {{ .Values.kuma.labels }}
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  resources:
    requests:
      storage: "500m"
  accessModes:
    - {{ .Values.kuma.volumes.accessModes }}