apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.postgresql.pv.volumeClaimName }}
    annotations:
        helm.sh/resource-policy: "keep"
spec:
    storageClassName: {{ .Values.pv.storageClass }}
    accessModes:
        - {{ .Values.kuma.volumes.accessModes }}
    resources:
        requests:
            storage: "1Gi"
    selector:
        matchLabels: 
            name: {{ .Values.postgresql.pv.labels }}